# Generated by Django 5.2.11 on 2026-02-18 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquationSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('a', models.FloatField(verbose_name='a koeffitsienti')),
                ('b', models.FloatField(verbose_name='b koeffitsienti')),
                ('c', models.FloatField(verbose_name='c koeffitsienti')),
                ('discriminant', models.FloatField(verbose_name='Diskriminant (D)')),
                ('roots', models.TextField(blank=True, verbose_name='Ildizlar')),
                ('steps', models.TextField(verbose_name='Bosqichlar')),
            ],
            options={
                'verbose_name': 'Yechim',
                'verbose_name_plural': 'Yechimlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
